### ISSUE TITLE
vers 1.5 association add does not work

### ISSUE THREAD

**Issue by arteck** [ioBroker/ioBroker.zwave#70] opened 2019-08-26 11:06 UTC
problem with ozw 1.6 and zwave 1.5 .. i can not add any node to association

getAllAssociationGroups or getAssociations does not work also.....

![grafik](https://user-images.githubusercontent.com/6681528/63686662-bd202100-c802-11e9-905a-b97085933972.png)

![grafik](https://user-images.githubusercontent.com/6681528/63686676-c7421f80-c802-11e9-8171-91204641c7b1.png)

but does not work.. after restart i cant see the shortcut

**Comment by carsten19** [comment] 2019-08-26 12:41
@AlCalzone any idea? I didn't test associations so far.

**Comment by AlCalzone** [comment] 2019-08-26 12:43
I discussed this with arteck already. No idea why its suddenly not working.

**Comment by carsten19** [comment] 2019-08-26 12:45
OK can I get a debug log as a starting point?

**Comment by carsten19** [comment] 2019-08-26 18:11
I just tried it with 2 Fibaro roller shutter:

2019-08-26 20:00:12.527  - info: zwave.0 Requesting all association groups from node 3
2019-08-26 20:00:16.899  - info: zwave.0 Requesting associations in group 1 from node 3
2019-08-26 20:00:16.917  - info: zwave.0 Requesting max number of associations in group 1 from node 3
2019-08-26 20:00:26.355  - info: zwave.0 Adding association with node 4 to group 1 of node 3

I have assigned the switch click to group 1.
--> works, so node 3 triggers node 4 on switch.

**Comment by carsten19** [comment] 2019-08-27 05:44
I have tried several combinations with add and remove and they all worked. I have seen an issue once but can't reproduce this anymore.
@arteck are the associations actually working and it's just a display issue? I will need a bit of help to reproduce it.

**Comment by arteck** [comment] 2019-08-28 17:39
i have here now a old version 1.4.2.. sry

**Comment by carsten19** [comment] 2019-08-28 17:44
Definitely works with the current version (1.5)

**Comment by carsten19** [comment] 2019-09-10 17:57
@arteck I will either need more information or we need to close the issue

**Closed as completed** 2019-09-15 10:42 UTC
